## Creando arreglos de una dimensión

In [2]:
import numpy as np
array = np.array([3, 33, 333]) # Crea un arreglo de dimensión 1 en numpy
print(type(array))

<class 'numpy.ndarray'>


In [6]:
print(array.shape) # Dimensión del array

(3,)


## Creando arreglos de dos dimensiones

In [8]:
another = np.array([[11, 12, 13], [21, 22, 23]])
print(another)
print("Las dimensiones son: ", another.shape)
print(another[0, 2])

[[11 12 13]
 [21 22 23]]
Las dimensiones son:  (2, 3)
13


## Diferentes maneras de crear un array en numpy

In [21]:
ex1 = np.zeros((2, 2))
print(ex1)
# Creando array lleno de 9
ex2 = np.full((2, 2), 9.0)
print(ex2)
print("Creando una matriz diagonal: ", end = "\n\n")
ex3 = np.eye(4, 4)
print(ex3)
print("\nCreamdo una matriz de unos: ", end = "\n\n")
ex4 = np.ones((5, 4))
print(ex4)

print("\nCreando array ccon valores al azar: ", end = "\n\n")
ex5 = np.random.random((2, 2))
print(ex5)

[[0. 0.]
 [0. 0.]]
[[9. 9.]
 [9. 9.]]
Creando una matriz diagonal: 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Creamdo una matriz de unos: 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Creando array ccon valores al azar: 

[[0.81900639 0.07067071]
 [0.1882174  0.89395043]]


## Slice indexing

In [28]:
array = np.array([[11, 12, 13, 14], [21, 22, 23, 24], [31, 32, 33, 34]])
print(array)
print("\n\nSlicing...")
slice = array[:3, 1:3]
s = np.array(slice) # Creando una copia del array
print(slice)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


Slicing...
[[12 13]
 [22 23]
 [32 33]]


In [29]:
np.arange(5)

array([0, 1, 2, 3, 4])